// Generated by gencpp from file a3_p2/ExtractedLines.msg
// DO NOT EDIT!


#ifndef A3_P2_MESSAGE_EXTRACTEDLINES_H
#define A3_P2_MESSAGE_EXTRACTEDLINES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <a3_p2/ExtractedLine.h>

namespace a3_p2
{
template <class ContainerAllocator>
struct ExtractedLines_
{
  typedef ExtractedLines_<ContainerAllocator> Type;

  ExtractedLines_()
    : header()
    , lines()  {
    }
  ExtractedLines_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lines(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::a3_p2::ExtractedLine_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::a3_p2::ExtractedLine_<ContainerAllocator> >::other >  _lines_type;
  _lines_type lines;





  typedef boost::shared_ptr< ::a3_p2::ExtractedLines_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::a3_p2::ExtractedLines_<ContainerAllocator> const> ConstPtr;

}; // struct ExtractedLines_

typedef ::a3_p2::ExtractedLines_<std::allocator<void> > ExtractedLines;

typedef boost::shared_ptr< ::a3_p2::ExtractedLines > ExtractedLinesPtr;
typedef boost::shared_ptr< ::a3_p2::ExtractedLines const> ExtractedLinesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::a3_p2::ExtractedLines_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::a3_p2::ExtractedLines_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace a3_p2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'a3_p2': ['/home/parallels/assignment_2/src/a3_p2/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::a3_p2::ExtractedLines_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a3_p2::ExtractedLines_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a3_p2::ExtractedLines_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a3_p2::ExtractedLines_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a3_p2::ExtractedLines_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a3_p2::ExtractedLines_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::a3_p2::ExtractedLines_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84df0150225154ce23ef2354bc707c6e";
  }

  static const char* value(const ::a3_p2::ExtractedLines_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84df0150225154ceULL;
  static const uint64_t static_value2 = 0x23ef2354bc707c6eULL;
};

template<class ContainerAllocator>
struct DataType< ::a3_p2::ExtractedLines_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3_p2/ExtractedLines";
  }

  static const char* value(const ::a3_p2::ExtractedLines_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::a3_p2::ExtractedLines_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
ExtractedLine[] lines\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: a3_p2/ExtractedLine\n\
# The r and alpha parameters define the extracted line.\n\
float32 r\n\
float32 alpha\n\
#\n\
# The following points are used for display / debugging purposes only.\n\
# These points come from the position of the first and last laser scan points\n\
# used to estimate the line. They do not define the line and may not have even\n\
# been used in estimating the line (e.g. they may have exceeded the\n\
# maximum_range parameter). However, they are useful in visualizing what range\n\
# of scan points were used to estimate the line.\n\
geometry_msgs/Point firstScanPoint\n\
geometry_msgs/Point lastScanPoint\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::a3_p2::ExtractedLines_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::a3_p2::ExtractedLines_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lines);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExtractedLines_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::a3_p2::ExtractedLines_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::a3_p2::ExtractedLines_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lines[]" << std::endl;
    for (size_t i = 0; i < v.lines.size(); ++i)
    {
      s << indent << "  lines[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::a3_p2::ExtractedLine_<ContainerAllocator> >::stream(s, indent + "    ", v.lines[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // A3_P2_MESSAGE_EXTRACTEDLINES_H
